language: c

env:
  global:
    - PAGER=cat

before_install:
  - sudo add-apt-repository -y ppa:cartodb/postgresql-9.5
  - sudo add-apt-repository -y ppa:cartodb/gis
  - sudo add-apt-repository -y ppa:cartodb/gis-testing

  # Needed for the compilation of odbc_fdw.c
  - sudo apt-get -y install unixodbc-dev

  # Force instalation of libgeos-3.5.0 (presumably needed because of existing version of postgis)
  - sudo apt-get -y install libgeos-3.5.0=3.5.0-1cdb2

  # Install postgres db and build deps
  - sudo /etc/init.d/postgresql stop # stop travis default instance
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgis
  - sudo apt-get -y autoremove

  - sudo apt-get -y install postgresql-9.5=9.5.2-2ubuntu1
  - sudo apt-get -y install postgresql-server-dev-9.5=9.5.2-2ubuntu1
  - sudo apt-get -y install postgresql-9.5-postgis-2.2=2.2.2.0-cdb2
  - sudo apt-get -y install postgresql-9.5-postgis-scripts=2.2.2.0-cdb2

  # configure it to accept local connections from postgres
  - echo -e "# TYPE  DATABASE        USER            ADDRESS                 METHOD \nlocal   all             postgres                                trust\nlocal   all             all                                     trust\nhost    all             all             127.0.0.1/32            trust" \
    | sudo tee /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart 9.5

install:
  - sudo make install

script:
  - make run_test || { cat test/regression.diffs; false; }
